### ISSUE TITLE
Headings contained in other elements do not render

### ISSUE THREAD

**Issue by ccassity** [psalmody/dynamic-scrollspy#7]
When a heading is a child of an element, it does not get rendered in the resulting list. Not sure if this was intentional.

For example, this h2 will not get rendered.
```
<h1>rendered</h1>
<h2>rendered</h2>
<h3>rendered</h3>
<div>
<h2>not rendered</h2>
</div>
```

**Comment by psalmody** [comment]
Yeah - I'm not sure there's a good workaround on that. Basically, your H tags have to be on the same level as each other - I'm using jQuery `.nextUntil` to find "child" headers. Since these tags aren't really children of each other, that's the best solution I could figure out.
