### ISSUE TITLE
Assumption of sequential H<N> tags causes issue with out-of-order links in nav

### ISSUE THREAD

**Issue by MattFellows** [psalmody/dynamic-scrollspy#9]
Given the following markup, the current tree generation gets the links in the wrong order:
```
<h2>1</h2>
<h3>2</h3>
<h4>3</h4>
<h2>4</h2>
<h4>5</h4>
```
Yields:
```
1
  2
    3
    5
4
```

I've submitted pull request #8 which solves the issue for me and may also solve issue #7

**Comment by psalmody** [comment]
As discussed in the PR comments, this is malformed HTML (for accessibility) wontfix at this point
